using System.Collections.Generic;

namespace GraphCalculator
{
    public sealed record FunctionHelp(
        string Name,
        string Signature,
        string Description,
        string Category = "Core",
        string HlslNote = "Direct or close equivalent");

    public static class FunctionCatalog
    {
        public static IReadOnlyList<FunctionHelp> Items { get; } = new[]
        {
            new FunctionHelp("sin", "sin(x)", "Sine. Complex-aware when x is complex.", "Trigonometry", "sin(x)"),
            new FunctionHelp("cos", "cos(x)", "Cosine. Complex-aware when x is complex.", "Trigonometry", "cos(x)"),
            new FunctionHelp("tan", "tan(x)", "Tangent. Complex-aware when x is complex.", "Trigonometry", "tan(x)"),
            new FunctionHelp("asin", "asin(x)", "Inverse sine for real inputs.", "Trigonometry", "asin(x)"),
            new FunctionHelp("acos", "acos(x)", "Inverse cosine for real inputs.", "Trigonometry", "acos(x)"),
            new FunctionHelp("atan", "atan(x)", "Inverse tangent for real inputs.", "Trigonometry", "atan(x)"),
            new FunctionHelp("atan2", "atan2(y,x)", "Quadrant-aware angle in radians.", "Trigonometry", "atan2(y,x)"),
            new FunctionHelp("sinh", "sinh(x)", "Hyperbolic sine. Complex-aware.", "Trigonometry", "sinh(x)"),
            new FunctionHelp("cosh", "cosh(x)", "Hyperbolic cosine. Complex-aware.", "Trigonometry", "cosh(x)"),
            new FunctionHelp("tanh", "tanh(x)", "Hyperbolic tangent. Complex-aware.", "Trigonometry", "tanh(x)"),
            new FunctionHelp("sqrt", "sqrt(x)", "Square root. In an advanced/complex expression, negative inputs may produce complex values.", "Core", "sqrt(x) for real; gc_csqrt for complex"),
            new FunctionHelp("abs", "abs(x)", "Absolute value for reals; magnitude |z| for complex values.", "Core", "abs(x) / length(z)"),
            new FunctionHelp("exp", "exp(x)", "e raised to x. Complex-aware.", "Core", "exp(x) / gc_cexp(z)"),
            new FunctionHelp("ln", "ln(x)", "Natural logarithm. Complex-aware.", "Core", "log(x) / gc_clog(z)"),
            new FunctionHelp("log", "log(x)", "Base-10 logarithm. Complex-aware.", "Core", "log10(x)"),
            new FunctionHelp("pow", "pow(x,p)", "Raise x to p. The ^ operator is equivalent and supports complex powers in advanced expressions.", "Core", "pow(x,p) / gc_cpow for complex"),
            new FunctionHelp("floor", "floor(x)", "Round downward to the nearest integer.", "Core", "floor(x)"),
            new FunctionHelp("ceil", "ceil(x)", "Round upward to the nearest integer.", "Core", "ceil(x)"),
            new FunctionHelp("round", "round(x)", "Round to the nearest integer.", "Core", "round(x)"),
            new FunctionHelp("sign", "sign(x)", "Return -1, 0 or 1 according to the sign of x.", "Core", "sign(x)"),
            new FunctionHelp("min", "min(a,b)", "Smaller of two real values.", "Core", "min(a,b)"),
            new FunctionHelp("max", "max(a,b)", "Larger of two real values.", "Core", "max(a,b)"),
            new FunctionHelp("clamp", "clamp(x,min,max)", "Clamp a real value to a range.", "Shaping", "clamp(x,min,max)"),
            new FunctionHelp("saturate", "saturate(x)", "Clamp to 0..1.", "Shaping", "saturate(x)"),
            new FunctionHelp("lerp", "lerp(a,b,t)", "Linear interpolation. a and b may be complex; t is real.", "Shaping", "lerp(a,b,t)"),
            new FunctionHelp("inverselerp", "inverselerp(a,b,x)", "Normalize x between a and b.", "Shaping", "gc_inverseLerp"),
            new FunctionHelp("remap", "remap(inMin,inMax,outMin,outMax,x)", "Map one range into another.", "Shaping", "gc_remap"),
            new FunctionHelp("step", "step(edge,x)", "0 below the edge, otherwise 1.", "Shaping", "step(edge,x)"),
            new FunctionHelp("smoothstep", "smoothstep(a,b,x)", "Cubic smooth transition.", "Shaping", "smoothstep(a,b,x)"),
            new FunctionHelp("smootherstep", "smootherstep(a,b,x)", "Quintic smooth transition.", "Shaping", "gc_smootherstep"),
            new FunctionHelp("frac", "frac(x)", "Fractional part.", "Core", "frac(x)"),
            new FunctionHelp("mod", "mod(x,y)", "Floor-based modulo.", "Core", "x-y*floor(x/y)"),
            new FunctionHelp("repeat", "repeat(x,length)", "Repeat x over a period.", "Shaping", "floor-based repeat"),
            new FunctionHelp("pingpong", "pingpong(x,length)", "Back-and-forth repeating value.", "Shaping", "gc_pingpong"),
            new FunctionHelp("if", "if(condition,a,b)", "Piecewise conditional; comparisons return 0 or 1.", "Logic", "ternary operator"),
            new FunctionHelp("and", "and(a,b)", "Numeric logical AND.", "Logic", "&& mapped to 0/1"),
            new FunctionHelp("or", "or(a,b)", "Numeric logical OR.", "Logic", "|| mapped to 0/1"),
            new FunctionHelp("not", "not(x)", "Numeric logical NOT.", "Logic", "comparison to zero"),
            new FunctionHelp("uniform", "uniform(min,max,r)", "Map a 0..1 random sample into a range.", "Probability", "lerp(min,max,saturate(r))"),
            new FunctionHelp("normal", "normal(mean,std,g)", "Map a standard-normal sample into a distribution.", "Probability", "mean + std*g"),
            new FunctionHelp("bernoulli", "bernoulli(p,r)", "1 when sample r succeeds probability p.", "Probability", "r < saturate(p)"),
            new FunctionHelp("noise", "noise(x,y)", "Deterministic value noise.", "Procedural", "gc_noise"),
            new FunctionHelp("noiseseed", "noiseseed(x,y,seed)", "Seeded value noise.", "Procedural", "gc_noise"),
            new FunctionHelp("fbm", "fbm(x,y,octaves,persistence,lacunarity)", "Layered value noise.", "Procedural", "gc_fbm"),
            new FunctionHelp("superformula", "superformula(angle,m,n1,n2,n3,a,b)", "Gielis superformula radius. Use it inside r(t)=(radius*cos(t),radius*sin(t)) to build stars, rounded polygons and organic profiles.", "Procedural", "gc_superformula"),

            new FunctionHelp("complex", "complex(real,imag)", "Construct real + imag·i.", "Complex", "float2(real,imag)"),
            new FunctionHelp("i", "i", "Imaginary unit √−1.", "Complex", "float2(0,1)"),
            new FunctionHelp("re", "re(z) / real(z)", "Real component of z.", "Complex", "z.x"),
            new FunctionHelp("im", "im(z) / imag(z)", "Imaginary component of z.", "Complex", "z.y"),
            new FunctionHelp("arg", "arg(z) / phase(z)", "Complex argument / phase in radians.", "Complex", "atan2(z.y,z.x)"),
            new FunctionHelp("conj", "conj(z)", "Complex conjugate.", "Complex", "float2(z.x,-z.y)"),
            new FunctionHelp("cis", "cis(angle)", "cos(angle) + i·sin(angle).", "Complex", "float2(cos(a),sin(a))"),
            new FunctionHelp("polar", "polar(radius,angle)", "Construct a complex value from polar coordinates.", "Complex", "r*float2(cos(a),sin(a))"),
            new FunctionHelp("csqrt", "csqrt(z)", "Explicit complex square root.", "Complex", "gc_csqrt"),
            new FunctionHelp("clog", "clog(z)", "Explicit complex natural logarithm.", "Complex", "gc_clog"),
            new FunctionHelp("cexp", "cexp(z)", "Explicit complex exponential.", "Complex", "gc_cexp"),
            new FunctionHelp("csin", "csin(z)", "Explicit complex sine.", "Complex", "gc_csin"),
            new FunctionHelp("ccos", "ccos(z)", "Explicit complex cosine.", "Complex", "gc_ccos"),
            new FunctionHelp("ctan", "ctan(z)", "Explicit complex tangent.", "Complex", "gc_cdiv(gc_csin(z),gc_ccos(z))"),

            new FunctionHelp("derivative", "derivative(expr,x[,h])", "Numerical derivative at the current variable value. Complex variables are supported; diff is an alias.", "Calculus", "CPU evaluator; write ddx/ddy only when screen-space derivatives are intended"),
            new FunctionHelp("integral", "integral(expr,x,a,b[,steps])", "Numerical definite integral. Complex bounds use the straight line from a to b as the contour.", "Calculus", "CPU evaluator; explicit loop needed in shader"),
            new FunctionHelp("primitive", "primitive(expr,x,origin[,steps])", "Numerical antiderivative from origin to the current variable value; complex values use a straight-line contour.", "Calculus", "CPU evaluator; explicit loop needed in shader"),
            new FunctionHelp("sum", "sum(expr,k,start,end)", "Finite summation with k bound inside expr.", "Series", "CPU evaluator; explicit loop in shader"),
            new FunctionHelp("product", "product(expr,k,start,end)", "Finite product with k bound inside expr.", "Series", "CPU evaluator; explicit loop in shader"),
            new FunctionHelp("recurrence", "recurrence(z[n+1]=expr, z[0]=seed, count)", "Paper-style bounded recurrence. The sequence name can be z, a, w, etc. z_{n+1}, z_n and z_0 forms are accepted too. recurrence/recur/sequence are aliases for the generic iterator.", "Recurrence", "CPU evaluator; write an explicit bounded shader loop for generic recurrence"),
            new FunctionHelp("iterate", "iterate(expr,seed,count)", "Compact bounded recurrence. z is the previous value, n is the iteration index, and c is the current x+iy point in a 2D field.", "Recurrence", "CPU evaluator; generic recurrence needs a shader loop"),
            new FunctionHelp("escape", "escape(z[n+1]=expr,z[0]=seed,count,radius)", "Escape-time recurrence. Returns the first escaping iteration, or count+1 when the value survives the full iteration budget, so final-step escape and survival remain distinct.", "Recurrence", "CPU evaluator; generic recurrence needs a shader loop"),

            new FunctionHelp("mandelbrot", "mandelbrot(x,y,iterations)", "Finite-iteration Mandelbrot survivor mask. With iterations=1 the surviving region is the radius-2 circle; increasing iterations carves it toward the Mandelbrot set.", "Fractals", "gc_mandelbrotMask"),
            new FunctionHelp("mandelbrotiter", "mandelbrotiter(x,y,iterations)", "Normalized Mandelbrot escape iteration; 1 is reserved for points that survive every requested iteration.", "Fractals", "gc_mandelbrotIter"),
            new FunctionHelp("mandelbrotsmooth", "mandelbrotsmooth(x,y,iterations)", "Smooth normalized escape-time value for boundary colouring. Use mandelbrot(...) instead when you want the circle-to-set construction animation.", "Fractals", "gc_mandelbrotIter(...,smooth=1)"),
            new FunctionHelp("julia", "julia(x,y,cReal,cImag,iterations)", "Binary Julia-set membership.", "Fractals", "gc_juliaMask"),
            new FunctionHelp("juliaiter", "juliaiter(x,y,cReal,cImag,iterations)", "Normalized Julia escape iteration.", "Fractals", "gc_juliaIter(...,smooth=0)"),
            new FunctionHelp("juliasmooth", "juliasmooth(x,y,cReal,cImag,iterations)", "Smooth normalized Julia escape value.", "Fractals", "gc_juliaIter(...,smooth=1)"),

            new FunctionHelp("curve", "curve(x(t),y(t))", "2D parametric curve.", "Plot wrappers", "Not a scalar HLSL function"),
            new FunctionHelp("curve3", "curve3(x(t),y(t),z(t))", "3D parametric curve.", "Plot wrappers", "Not a scalar HLSL function"),
            new FunctionHelp("surface", "surface(x(u,v),y(u,v),z(u,v))", "3D parametric surface.", "Plot wrappers", "Not a scalar HLSL function"),
            new FunctionHelp("field", "field(vx(x,y),vy(x,y))", "2D vector field.", "Plot wrappers", "Not a scalar HLSL function"),
            new FunctionHelp("implicit", "implicit(f(x,y))", "2D zero contour f(x,y)=0.", "Plot wrappers", "Scalar body can be exported"),
            new FunctionHelp("implicit3", "implicit3(f(x,y,z))", "3D zero isosurface f(x,y,z)=0.", "Plot wrappers", "Scalar body can be exported"),
            new FunctionHelp("texture", "texture(f(x,y))", "2D scalar field rendered as a texture.", "Plot wrappers", "Scalar body can be exported"),
            new FunctionHelp("complexmap", "complexmap(f(z))", "Domain-colour a complex function over the x+iy plane. domain(...) is an alias.", "Plot wrappers", "Use float2 complex helpers in HLSL")
        };
    }
}
