<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\CalcLogo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\CalcLogo.ico" />
    <None Remove="Assets\CalcLogo-64.png" />
    <Resource Include="Assets\CalcLogo.ico" />
    <Resource Include="Assets\CalcLogo-64.png" />
  </ItemGroup>

</Project>
